CREATE TABLE IF NOT EXISTS public.submission_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL,
  fingerprint_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT submission_attempts_kind_check CHECK (kind IN ('contact','career','quote','booking','media'))
);
CREATE INDEX IF NOT EXISTS submission_attempts_rate_idx
  ON public.submission_attempts (kind, fingerprint_hash, created_at DESC);
GRANT ALL ON public.submission_attempts TO service_role;
ALTER TABLE public.submission_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.submission_attempts FROM anon, authenticated;

CREATE OR REPLACE FUNCTION private.consume_submission_attempt(
  p_kind TEXT,
  p_fingerprint_hash TEXT,
  p_limit INTEGER DEFAULT 6,
  p_window INTERVAL DEFAULT interval '15 minutes'
) RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  recent_count INTEGER;
BEGIN
  IF p_kind NOT IN ('contact','career','quote','booking','media') THEN
    RETURN false;
  END IF;

  DELETE FROM public.submission_attempts
  WHERE created_at < now() - interval '48 hours';

  SELECT count(*) INTO recent_count
  FROM public.submission_attempts
  WHERE kind = p_kind
    AND fingerprint_hash = p_fingerprint_hash
    AND created_at >= now() - p_window;

  IF recent_count >= p_limit THEN
    RETURN false;
  END IF;

  INSERT INTO public.submission_attempts(kind, fingerprint_hash)
  VALUES (p_kind, p_fingerprint_hash);

  RETURN true;
END;
$$;
REVOKE ALL ON FUNCTION private.consume_submission_attempt(TEXT, TEXT, INTEGER, INTERVAL)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.consume_submission_attempt(TEXT, TEXT, INTEGER, INTERVAL)
  TO service_role;
