-- Production hardening for Tranquility Level Cleaning.

CREATE OR REPLACE FUNCTION private.is_owner()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = auth, public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM auth.users u
    WHERE u.id = auth.uid()
      AND lower(u.email) = 'tlcllc26@gmail.com'
      AND u.email_confirmed_at IS NOT NULL
  )
$$;
REVOKE ALL ON FUNCTION private.is_owner() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION private.is_owner() TO authenticated, service_role;

DROP POLICY IF EXISTS "Admins manage availability blocks" ON public.availability_blocks;
CREATE POLICY "Verified owner manages availability blocks"
ON public.availability_blocks FOR ALL TO authenticated
USING (private.is_owner())
WITH CHECK (private.is_owner() AND created_by = auth.uid());

DROP POLICY IF EXISTS "Admins manage booking requests" ON public.booking_holds;
CREATE POLICY "Verified owner manages booking requests"
ON public.booking_holds FOR ALL TO authenticated
USING (private.is_owner())
WITH CHECK (private.is_owner());

DROP POLICY IF EXISTS "Admins manage quote requests" ON public.quote_requests;
CREATE POLICY "Verified owner manages quote requests"
ON public.quote_requests FOR ALL TO authenticated
USING (private.is_owner())
WITH CHECK (private.is_owner());

DROP POLICY IF EXISTS "Admins manage career applications" ON public.career_applications;
CREATE POLICY "Verified owner manages career applications"
ON public.career_applications FOR ALL TO authenticated
USING (private.is_owner())
WITH CHECK (private.is_owner());

DROP POLICY IF EXISTS "Admins manage contact inquiries" ON public.contact_inquiries;
CREATE POLICY "Verified owner manages contact inquiries"
ON public.contact_inquiries FOR ALL TO authenticated
USING (private.is_owner())
WITH CHECK (private.is_owner());

ALTER TABLE public.quote_requests
  ADD COLUMN IF NOT EXISTS upload_token_hash BYTEA,
  ADD COLUMN IF NOT EXISTS upload_token_expires_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS public.quote_media (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_request_id UUID NOT NULL REFERENCES public.quote_requests(id) ON DELETE CASCADE,
  object_path TEXT NOT NULL UNIQUE,
  file_name TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size_bytes BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT quote_media_size_check CHECK (size_bytes > 0 AND size_bytes <= 8388608),
  CONSTRAINT quote_media_mime_check CHECK (mime_type IN ('image/jpeg','image/png','image/webp','image/heic','image/heif'))
);
CREATE INDEX IF NOT EXISTS quote_media_quote_idx ON public.quote_media (quote_request_id, created_at);
GRANT SELECT, DELETE ON public.quote_media TO authenticated;
GRANT ALL ON public.quote_media TO service_role;
ALTER TABLE public.quote_media ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Verified owner reads quote media" ON public.quote_media;
CREATE POLICY "Verified owner reads quote media"
ON public.quote_media FOR SELECT TO authenticated
USING (private.is_owner());
DROP POLICY IF EXISTS "Verified owner deletes quote media" ON public.quote_media;
CREATE POLICY "Verified owner deletes quote media"
ON public.quote_media FOR DELETE TO authenticated
USING (private.is_owner());

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'quote-media',
  'quote-media',
  false,
  8388608,
  ARRAY['image/jpeg','image/png','image/webp','image/heic','image/heif']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "Verified owner reads quote-media objects" ON storage.objects;
CREATE POLICY "Verified owner reads quote-media objects"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'quote-media' AND private.is_owner());

DROP POLICY IF EXISTS "Verified owner deletes quote-media objects" ON storage.objects;
CREATE POLICY "Verified owner deletes quote-media objects"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'quote-media' AND private.is_owner());

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id UUID,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id UUID,
  old_values JSONB,
  new_values JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_logs_created_idx ON public.audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_entity_idx ON public.audit_logs (entity_type, entity_id, created_at DESC);
GRANT SELECT ON public.audit_logs TO authenticated;
GRANT ALL ON public.audit_logs TO service_role;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Verified owner reads audit logs" ON public.audit_logs;
CREATE POLICY "Verified owner reads audit logs"
ON public.audit_logs FOR SELECT TO authenticated
USING (private.is_owner());

CREATE OR REPLACE FUNCTION private.audit_owner_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  row_id UUID;
BEGIN
  row_id := COALESCE(NEW.id, OLD.id);
  INSERT INTO public.audit_logs(actor_user_id, action, entity_type, entity_id, old_values, new_values)
  VALUES (
    auth.uid(),
    TG_OP,
    TG_TABLE_NAME,
    row_id,
    CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) ELSE NULL END
  );
  RETURN COALESCE(NEW, OLD);
END;
$$;
REVOKE ALL ON FUNCTION private.audit_owner_mutation() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.audit_owner_mutation() TO service_role;

DROP TRIGGER IF EXISTS audit_booking_holds ON public.booking_holds;
CREATE TRIGGER audit_booking_holds AFTER UPDATE OR DELETE ON public.booking_holds
FOR EACH ROW EXECUTE FUNCTION private.audit_owner_mutation();

DROP TRIGGER IF EXISTS audit_quote_requests ON public.quote_requests;
CREATE TRIGGER audit_quote_requests AFTER UPDATE OR DELETE ON public.quote_requests
FOR EACH ROW EXECUTE FUNCTION private.audit_owner_mutation();

DROP TRIGGER IF EXISTS audit_career_applications ON public.career_applications;
CREATE TRIGGER audit_career_applications AFTER UPDATE OR DELETE ON public.career_applications
FOR EACH ROW EXECUTE FUNCTION private.audit_owner_mutation();

DROP TRIGGER IF EXISTS audit_contact_inquiries ON public.contact_inquiries;
CREATE TRIGGER audit_contact_inquiries AFTER UPDATE OR DELETE ON public.contact_inquiries
FOR EACH ROW EXECUTE FUNCTION private.audit_owner_mutation();

DROP TRIGGER IF EXISTS audit_availability_blocks ON public.availability_blocks;
CREATE TRIGGER audit_availability_blocks AFTER INSERT OR UPDATE OR DELETE ON public.availability_blocks
FOR EACH ROW EXECUTE FUNCTION private.audit_owner_mutation();

ALTER TABLE public.contact_inquiries
  DROP CONSTRAINT IF EXISTS contact_inquiries_language_check,
  ADD CONSTRAINT contact_inquiries_language_check CHECK (language IN ('en','es')),
  DROP CONSTRAINT IF EXISTS contact_inquiries_service_type_check,
  ADD CONSTRAINT contact_inquiries_service_type_check CHECK (service_type IN ('standard','deep','move','commercial','quote','other'));

ALTER TABLE public.career_applications
  DROP CONSTRAINT IF EXISTS career_applications_language_check,
  ADD CONSTRAINT career_applications_language_check CHECK (language IN ('en','es'));

ALTER TABLE public.quote_requests
  DROP CONSTRAINT IF EXISTS quote_requests_language_check,
  ADD CONSTRAINT quote_requests_language_check CHECK (language IN ('en','es')),
  DROP CONSTRAINT IF EXISTS quote_requests_property_type_check,
  ADD CONSTRAINT quote_requests_property_type_check CHECK (property_type IN ('residential','commercial','specialty')),
  DROP CONSTRAINT IF EXISTS quote_requests_contact_preference_check,
  ADD CONSTRAINT quote_requests_contact_preference_check CHECK (contact_preference IN ('phone','email','text','video'));

CREATE INDEX IF NOT EXISTS contact_inquiries_email_idx ON public.contact_inquiries (lower(email));
CREATE INDEX IF NOT EXISTS quote_requests_email_idx ON public.quote_requests (lower(email));
CREATE INDEX IF NOT EXISTS career_applications_email_idx ON public.career_applications (lower(email));
